### ISSUE TITLE
アルゴリズムについて

### ISSUE THREAD

**Issue by taka0913** [toshipon/bitcoin-arbitrage#1]
自分の知識不足でプログラムの解読が困難なので教えて頂きたいのですがこれはどういったアルゴリズムで売買の判定を行っているのでしょうか？

**Comment by toshipon** [comment]
@taka0913 特定のアルゴリズムがあるっていうわけではないのですが、アビトラージ（サヤ取り）の原則に沿って取引を行うようになっています。以下を参考ください。

https://medium.com/@toshipon/bitcoin%E3%81%AE%E3%82%A2%E3%83%BC%E3%83%93%E3%83%88%E3%83%A9%E3%83%BC%E3%82%B8%E5%8F%96%E5%BC%95bot%E3%82%92%E5%8B%95%E3%81%8B%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B-f5a586646fef

ただ、このプログラムでちゃんと稼げたことはないのであくまでご参考程度に見ていただければと思います。 mm

**Comment by taka0913** [comment]
なるほど…つまりzaifのアカウントだけではダメということでしたか…

面白い方法なので参考にさせて頂きます！
